In [1]:
import pandas as pd
import numpy as np

Marcos de datos

In [6]:
data = [
    ['Nisan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia', 2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders', 'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [7]:
df = pd.DataFrame(data, columns=columns)
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nisan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [11]:
data = [
    {
        'Make': 'Nisan',   
        'Model': 'Stanza',   
        'Year': 1991, 
        'Engine HP': 138,  
        'Engine Cylinders': 4, 
        'Transmission Type': 'MANUAL',    
        'Vehicle Style': 'sedan',       
        'MSRP': 2000
    },
    {
        'Make': 'Hyundai', 
        'Model': 'Sonata',   
        'Year': 2017, 
        'Engine HP': None, 
        'Engine Cylinders': 4, 
        'Transmission Type': 'AUTOMATIC', 
        'Vehicle Style': 'Sedan',       
        'MSRP': 27150
    },
    {
        'Make': 'Lotus',   
        'Model': 'Elise',    
        'Year': 2010, 'Engine HP': 218,  
        'Engine Cylinders': 4, 
        'Transmission Type': 'MANUAL',    
        'Vehicle Style': 'convertible', 
        'MSRP': 54990
    },
    {
        'Make': 'GMC',     
        'Model': 'Acadia',   
        'Year': 2017, 
        'Engine HP': 194,  
        'Engine Cylinders': 4, 
        'Transmission Type': 'AUTOMATIC', 
        'Vehicle Style': '4dr SUV',     
        'MSRP': 34450
    },
    {
        'Make': 'Nissan',  
        'Model': 'Frontier', 
        'Year': 2017, 
        'Engine HP': 261,  
        'Engine Cylinders': 6, 
        'Transmission Type': 'MANUAL',    
        'Vehicle Style': 'Pickup',      
        'MSRP': 32340
    },
]

In [20]:
df = pd.DataFrame(data)
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle Style,MSRP
0,Nisan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [21]:
df.head(n=2)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle Style,MSRP
0,Nisan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150

Series

In [22]:
df.Make

0      Nisan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: str

In [24]:
df[['Make', 'Model', 'MSRP']]

      Make     Model   MSRP
0    Nisan    Stanza   2000
1  Hyundai    Sonata  27150
2    Lotus     Elise  54990
3      GMC    Acadia  34450
4   Nissan  Frontier  32340

In [31]:
df['id'] = [1, 2, 3, 4, 5]

In [33]:
df['id'] = [10, 20, 30, 40, 50]

In [34]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle Style,MSRP,id
0,Nisan,Stanza,1991,138.0,4,MANUAL,sedan,2000,10
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,20
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,30
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,40
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,50

In [35]:
del df['id']

In [36]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle Style,MSRP
0,Nisan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

Indices

In [37]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [40]:
df.Make.index

RangeIndex(start=0, stop=5, step=1)

In [41]:
df.index = ['a', 'b', 'c', 'd', 'e']

In [42]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle Style,MSRP
a,Nisan,Stanza,1991,138.0,4,MANUAL,sedan,2000
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [43]:
df.loc[['b', 'c']]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle Style,MSRP
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990

In [45]:
df.iloc[1]

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle Style            Sedan
MSRP                     27150
Name: b, dtype: object

In [56]:
df = df.reset_index(drop= True)

In [57]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle Style,MSRP
0,Nisan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

Acceso a elementos

Operaciones con elementos

In [58]:
df['Engine HP'] / 100

0    1.38
1     NaN
2    2.18
3    1.94
4    2.61
Name: Engine HP, dtype: float64

In [59]:
df['Year'] >= 2015

0    False
1     True
2    False
3     True
4     True
Name: Year, dtype: bool

Filtros

In [60]:
df[
    df['Year'] >= 2015
]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle Style,MSRP
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [62]:
df[
    (df['Make'] == 'Nissan') & (df['Year'] >= 2015)
]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle Style,MSRP
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

Operaciones de Cadenas

In [68]:
'machine learning zoomcamp'.replace(' ', '_')

'machine_learning_zoomcamp'

In [69]:
'STRr'.lower()

'strr'

In [70]:
df['Vehicle Style'].str.lower()

0          sedan
1          sedan
2    convertible
3        4dr suv
4         pickup
Name: Vehicle Style, dtype: str

Resumen

In [71]:
df.MSRP.describe()

count        5.000000
mean     30186.000000
std      18985.044904
min       2000.000000
25%      27150.000000
50%      32340.000000
75%      34450.000000
max      54990.000000
Name: MSRP, dtype: float64

Valores faltantes

In [72]:
df.isnull()

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle Style,MSRP
0,False,False,False,False,False,False,False,False
1,False,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False

In [73]:
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle Style        0
MSRP                 0
dtype: int64

Grupos

SELECT 
    transmission_type,
    AVG(MSRP)
FROM
    cars
GROUP BY
    transmission_type

In [81]:
df.groupby('Transmission Type').MSRP.mean()

Transmission Type
AUTOMATIC    30800.000000
MANUAL       29776.666667
Name: MSRP, dtype: float64

Obtener el array de NumPy

In [82]:
df.MSRP.values

array([ 2000, 27150, 54990, 34450, 32340])

In [84]:
df.to_dict(orient='records')

[{'Make': 'Nisan',
  'Model': 'Stanza',
  'Year': 1991,
  'Engine HP': 138.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle Style': 'sedan',
  'MSRP': 2000},
 {'Make': 'Hyundai',
  'Model': 'Sonata',
  'Year': 2017,
  'Engine HP': nan,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle Style': 'Sedan',
  'MSRP': 27150},
 {'Make': 'Lotus',
  'Model': 'Elise',
  'Year': 2010,
  'Engine HP': 218.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle Style': 'convertible',
  'MSRP': 54990},
 {'Make': 'GMC',
  'Model': 'Acadia',
  'Year': 2017,
  'Engine HP': 194.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle Style': '4dr SUV',
  'MSRP': 34450},
 {'Make': 'Nissan',
  'Model': 'Frontier',
  'Year': 2017,
  'Engine HP': 261.0,
  'Engine Cylinders': 6,
  'Transmission Type': 'MANUAL',
  'Vehicle Style': 'Pickup',
  'MSRP': 32340}]